window.$ = window.jQuery = require("jquery");
require("bootstrap");
require("bootstrap-select/dist/js/bootstrap-select");
require("socicon/css/socicon.css");
require("@fortawesome/fontawesome-free/css/all.min.css");
require("./_metronic/_assets/plugins/line-awesome/css/line-awesome.css");
require("./_metronic/_assets/plugins/flaticon/flaticon.css");
require("./_metronic/_assets/plugins/flaticon2/flaticon.css");
require("./_metronic/_assets/plugins/daterangepicker/daterangepicker.js");
require("./_metronic/_assets/plugins/daterangepicker/daterangepicker.css");
require("moment/locale/th");
